"""make audit_log artifact_id nullable

Revision ID: 1e21fe7f9594
Revises: d9891577bd03
Create Date: 2026-04-28 14:48:37.612942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e21fe7f9594'
down_revision: Union[str, Sequence[str], None] = 'd9891577bd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'artifact_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'artifact_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
